name = "Chicken"
license = "MIT"
licenselink = "https://github.com/huhndev/chicken/blob/master/LICENSE"
description = "Minimal dev blog."
homepage = "https://github.com/huhndev/chicken"
tags = ["blog"]
features = ["blog"]
min_version = "0.139"

[author]
  name = "Julian Huhn"
  homepage = "https://huhn.dev"

[original]
  name = "Benny Mei"
  homepage = "https://gitlab.com/meibenny/elephants"
