baseURL = "https://huhn.dev/"
title = "huhn.dev"
theme = "chicken"

disableKinds = ["taxonomy", "sitemap"]

[permalinks]
  blog = "/:title/"

[params]
  sitename = "huhn.dev"
  description = "A minimal dev blog by Julian Huhn."
  #cv = "https://huhn.dev/cv"

[outputs]
  home     = ["HTML"]
  section  = ["HTML", "RSS"]

[outputFormats]
[outputFormats.RSS]
mediatype = "application/rss+xml"
baseName = "rss"
